/**
 * src/models/message.model.js — Message Mongoose Model
 *
 * Stores chat messages between users.
 * Uses a "roomId" convention (sorted user IDs) to identify conversations
 * without needing a separate Conversation collection.
 */

const mongoose = require("mongoose");

// Supported message content types
const MESSAGE_TYPES = ["text", "image", "file", "system"];

const messageSchema = new mongoose.Schema(
  {
    // ── Participants ─────────────────────────────────────────────────────────

    sender: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Sender is required"],
    },

    receiver: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Receiver is required"],
    },

    /**
     * roomId: deterministic combined key for the conversation.
     * Generated by sorting [senderId, receiverId] alphabetically and joining
     * with "_". This ensures the same room is referenced regardless of
     * who initiates.
     *
     * Example: "64f3a_64f3b" (always the same for that pair)
     */
    roomId: {
      type: String,
      required: true,
      index: true, // Most queries are room-scoped, so index heavily
    },

    // ── Content ──────────────────────────────────────────────────────────────

    content: {
      type: String,
      required: [true, "Message content is required"],
      trim: true,
      maxlength: [2000, "Message cannot exceed 2000 characters"],
    },

    type: {
      type: String,
      enum: MESSAGE_TYPES,
      default: "text",
    },

    // ── Status ───────────────────────────────────────────────────────────────

    isRead: {
      type: Boolean,
      default: false,
    },

    readAt: {
      type: Date,
      default: null,
    },

    isDeleted: {
      type: Boolean,
      default: false, // soft-delete — message is hidden but not removed from DB
    },
  },
  {
    timestamps: true, // createdAt = message timestamp, updatedAt tracks edits
  }
);

// ── Compound Index ────────────────────────────────────────────────────────────
// Optimise "get messages in room sorted by time" — the most common query
messageSchema.index({ roomId: 1, createdAt: 1 });

// ── Static Method: Generate Room ID ──────────────────────────────────────────
/**
 * Generates a deterministic room ID from two user IDs.
 * Sorting ensures the same ID regardless of who sends first.
 *
 * @param {string} userId1
 * @param {string} userId2
 * @returns {string}
 */
messageSchema.statics.generateRoomId = function (userId1, userId2) {
  return [userId1.toString(), userId2.toString()].sort().join("_");
};

const Message = mongoose.model("Message", messageSchema);
module.exports = Message;
